dev_ocr:
	ansible-playbook -i ./hosts site.yml --extra-vars "env=dev server=ocr"

stg_ocr:
	ansible-playbook -i ./hosts site.yml --extra-vars "env=stg server=ocr"

uat_ocr:
	ansible-playbook -i ./hosts site.yml --extra-vars "env=uat server=ocr"

prd_ocr:
	ansible-playbook -i ./hosts site.yml --extra-vars "env=prd server=ocr"

# more servers can be defined here